import { addSuffixToKeys } from "@grind-t/toolkit/object";
import * as v from "valibot";

const capitalRow = <T extends string>(code: T) =>
	addSuffixToKeys(
		{
			expl: v.nullish(v.string()),
			authorized: v.nullish(v.number()),
			additional: v.nullish(v.number()),
			reserve: v.nullish(v.number()),
			unallocated: v.nullish(v.number()),
			redeemed: v.nullish(v.number()),
			revaluation: v.nullish(v.number()),
			total: v.nullish(v.number()),
		},
		code,
	);

const adjustmentRow = <T extends string>(code: T) =>
	addSuffixToKeys(
		{
			netProfitLoss: v.nullish(v.number()),
			otherFactors: v.nullish(v.number()),
			previous: v.nullish(v.number()),
			beforePrevious: v.nullish(v.number()),
		},
		code,
	);

const extendedAdjustmentRow = <T extends string>(code: T) =>
	addSuffixToKeys(
		{
			netProfitLoss: v.nullish(v.number()),
			otherFactors: v.nullish(v.number()),
			previous: v.nullish(v.number()),
			beforePrevious: v.nullish(v.number()),
			authorized: v.nullish(v.number()),
			additional: v.nullish(v.number()),
			unallocated: v.nullish(v.number()),
			total: v.nullish(v.number()),
		},
		code,
	);

// Новые коды - https://tinyurl.com/mvwfhaav
// Старые коды - https://tinyurl.com/mr475uc8
export const CapitalChangeSchema = v.strictObject({
	id: v.number(),
	okud: v.string(),
	...capitalRow("3100"),
	...capitalRow("3101"),
	...capitalRow("3110"),
	...capitalRow("3120"),
	...capitalRow("3200"),
	...capitalRow("3201"),
	...capitalRow("3210"),
	...capitalRow("3211"),
	...capitalRow("3212"),
	...capitalRow("3213"),
	...capitalRow("3214"),
	...capitalRow("3215"),
	...capitalRow("3216"),
	...capitalRow("3220"),
	...capitalRow("3221"),
	...capitalRow("3222"),
	...capitalRow("3223"),
	...capitalRow("3224"),
	...capitalRow("3225"),
	...capitalRow("3226"),
	...capitalRow("3227"),
	...capitalRow("3230"),
	...capitalRow("3231"),
	...capitalRow("3232"),
	...capitalRow("3240"),
	...capitalRow("3241"),
	...capitalRow("3242"),
	...capitalRow("3250"),
	...capitalRow("3300"),
	...capitalRow("3310"),
	...capitalRow("3311"),
	...capitalRow("3312"),
	...capitalRow("3313"),
	...capitalRow("3314"),
	...capitalRow("3315"),
	...capitalRow("3316"),
	...capitalRow("3320"),
	...capitalRow("3321"),
	...capitalRow("3322"),
	...capitalRow("3323"),
	...capitalRow("3324"),
	...capitalRow("3325"),
	...capitalRow("3326"),
	...capitalRow("3327"),
	...capitalRow("3330"),
	...capitalRow("3331"),
	...capitalRow("3332"),
	...capitalRow("3340"),
	...capitalRow("3341"),
	...capitalRow("3342"),
	...adjustmentRow("3400"),
	...adjustmentRow("3401"),
	...adjustmentRow("3402"),
	...adjustmentRow("3410"),
	...adjustmentRow("3411"),
	...adjustmentRow("3412"),
	...extendedAdjustmentRow("3420"),
	...extendedAdjustmentRow("3421"),
	...extendedAdjustmentRow("3422"),
	...adjustmentRow("3500"),
	...adjustmentRow("3501"),
	...adjustmentRow("3502"),
	current3600: v.nullish(v.number()),
	previous3600: v.nullish(v.number()),
	beforePrevious3600: v.nullish(v.number()),
});
